name: freedium_mobile
description: "An app to read Medium articles without hitting the paywall"
publish_to: "none"
version: 0.8.0

environment:
  sdk: ^3.10.0

dependencies:
  dynamic_color: ^1.8.1
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.13
  flutter_markdown_plus: ^1.0.7
  flutter_riverpod: ^3.2.1
  http: ^1.6.0
  listen_sharing_intent: ^1.9.2
  pub_semver: ^2.2.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  # custom_lint: ^0.8.1
  riverpod_lint: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/js/
    - assets/css/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path_android: "assets/icon/ic_launcher.png"
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icon/ic_launcher_monochrome.png"
  min_sdk_android: 21
  image_path_ios: "assets/icon/icon.png"
